### PR TITLE
Replace autohiding event handler with no-op.

### PR DESCRIPTION
**Pull request by jimkang**
After the control bar is loaded, replace the play event handler with a no-op so that the bar doesn't get hidden. This approach was chosen so that the core (04_video_container.js) would not have to be modified.

### CODE REVIEW

**Comment by spiraleddy** [comment]
+1 elegant, non invasive, and easy to identify as a DCE'ism

**Comment by lbjay** [comment]
LGTM

**Comment by djcp** [comment]
As long as this doesn't effect the handler for other modules, go for it! I'm sure you thought of that, though.

**Comment by jimkang** [comment]
@djcp Right, `restartHideTimer` is entirely concerned with autohiding, and nothing outside of `04_video_container.js` and `06_ui_controls.js` refer to it.

**Comment by jimkang** [comment]
QA'd. Merging.

**Pull request merged**
